import type { MemeTemplate, MemeThumbnailCrop } from '../types';

function resolveTemplateUrl(url: string) {
  if (!url.startsWith('/')) {
    return url;
  }

  return `${import.meta.env.BASE_URL}${url.slice(1)}`;
}

const THUMBNAIL_RATIO_TOLERANCE = 0.005;

/**
 * Validate an optional thumbnail crop. Returns the crop when it is well-formed,
 * `null` when it should be dropped (warns the caller-supplied label so authors
 * notice in the console), and `undefined` when the field is absent.
 */
function validateThumbnail(value: unknown, label: string): MemeThumbnailCrop | null | undefined {
  if (value === undefined || value === null) {
    return undefined;
  }
  if (typeof value !== 'object') {
    console.warn(`Template "${label}" has a non-object thumbnail; ignoring.`);
    return null;
  }
  const crop = value as Partial<MemeThumbnailCrop>;
  const numbers: (keyof MemeThumbnailCrop)[] = ['x', 'y', 'width', 'height'];
  for (const key of numbers) {
    const num = crop[key];
    if (typeof num !== 'number' || !Number.isFinite(num) || num < 0 || num > 1) {
      console.warn(`Template "${label}" has an out-of-range thumbnail.${key}; ignoring crop.`);
      return null;
    }
  }
  const { x, y, width, height } = crop as MemeThumbnailCrop;
  if (width <= 0 || height <= 0 || x + width > 1 + 1e-6 || y + height > 1 + 1e-6) {
    console.warn(`Template "${label}" has a thumbnail that escapes the image; ignoring crop.`);
    return null;
  }
  if (Math.abs(width / height - 4 / 3) > THUMBNAIL_RATIO_TOLERANCE) {
    console.warn(`Template "${label}" thumbnail is not 4:3; ignoring crop.`);
    return null;
  }
  return { x, y, width, height };
}

function isMemeTemplate(value: unknown): value is MemeTemplate {
  if (!value || typeof value !== 'object') {
    return false;
  }

  const template = value as Partial<MemeTemplate>;

  return (
    typeof template.id === 'string' &&
    typeof template.name === 'string' &&
    typeof template.url === 'string' &&
    Array.isArray(template.tags) &&
    Array.isArray(template.textFields) &&
    template.textFields.every((field) => {
      return (
        field &&
        typeof field.id === 'string' &&
        typeof field.placeholder === 'string' &&
        typeof field.x === 'number' &&
        typeof field.y === 'number' &&
        typeof field.width === 'number' &&
        typeof field.height === 'number' &&
        typeof field.fontSize === 'number' &&
        typeof field.color === 'string' &&
        ['left', 'center', 'right'].includes(field.align) &&
        (field.rotation === undefined || typeof field.rotation === 'number')
      );
    })
  );
}

/**
 * Loads all meme templates with a single network round-trip.
 *
 * `public/memes/index.json` is generated by `vite-plugin-meme-manifest` and
 * inlines every template's full JSON, so we don't pay N+1 fetches as the
 * template count grows.
 *
 * To add a template: drop a PNG/JPG/SVG into `public/memes/` and a sibling
 * JSON next to it — the plugin updates the manifest on the next dev tick or
 * build. Invalid entries are warned to console and skipped, not thrown.
 */
export async function loadMemeTemplates(): Promise<MemeTemplate[]> {
  const manifestUrl = `${import.meta.env.BASE_URL}memes/index.json`;
  let manifestResponse: Response;
  try {
    manifestResponse = await fetch(manifestUrl);
  } catch (err) {
    console.warn('Failed to fetch meme manifest:', err);
    return [];
  }

  if (!manifestResponse.ok) {
    console.warn(`Failed to fetch meme manifest: HTTP ${manifestResponse.status}`);
    return [];
  }

  let entries: unknown;
  try {
    entries = await manifestResponse.json();
  } catch (err) {
    console.warn('Meme manifest is not valid JSON:', err);
    return [];
  }

  if (!Array.isArray(entries)) {
    console.warn('Meme manifest must be a JSON array of template objects.');
    return [];
  }

  return entries
    .map((entry, index) => {
      if (!isMemeTemplate(entry)) {
        const label =
          entry && typeof entry === 'object' && 'id' in entry && typeof (entry as { id: unknown }).id === 'string'
            ? (entry as { id: string }).id
            : `index ${index}`;
        console.warn(`Skipped invalid meme template: ${label}`);
        return null;
      }
      const thumbnail = validateThumbnail((entry as { thumbnail?: unknown }).thumbnail, entry.id);
      const { thumbnail: _stripped, ...rest } = entry as MemeTemplate & { thumbnail?: unknown };
      void _stripped;
      const next: MemeTemplate = { ...rest, url: resolveTemplateUrl(entry.url) };
      if (thumbnail) {
        next.thumbnail = thumbnail;
      }
      return next;
    })
    .filter((template): template is MemeTemplate => template !== null)
    .sort((a, b) => a.name.localeCompare(b.name));
}
