import type { MemeTemplate } from '../types';

function resolveTemplateUrl(url: string) {
  if (!url.startsWith('/')) {
    return url;
  }

  return `${import.meta.env.BASE_URL}${url.slice(1)}`;
}

function isMemeTemplate(value: unknown): value is MemeTemplate {
  if (!value || typeof value !== 'object') {
    return false;
  }

  const template = value as Partial<MemeTemplate>;

  return (
    typeof template.id === 'string' &&
    typeof template.name === 'string' &&
    typeof template.url === 'string' &&
    Array.isArray(template.tags) &&
    Array.isArray(template.textFields) &&
    template.textFields.every((field) => {
      return (
        field &&
        typeof field.id === 'string' &&
        typeof field.placeholder === 'string' &&
        typeof field.x === 'number' &&
        typeof field.y === 'number' &&
        typeof field.width === 'number' &&
        typeof field.height === 'number' &&
        typeof field.fontSize === 'number' &&
        typeof field.color === 'string' &&
        ['left', 'center', 'right'].includes(field.align)
      );
    })
  );
}

/**
 * Loads all meme templates with a single network round-trip.
 *
 * `public/memes/index.json` is generated by `vite-plugin-meme-manifest` and
 * inlines every template's full JSON, so we don't pay N+1 fetches as the
 * template count grows.
 *
 * To add a template: drop a PNG/JPG/SVG into `public/memes/` and a sibling
 * JSON next to it — the plugin updates the manifest on the next dev tick or
 * build. Invalid entries are warned to console and skipped, not thrown.
 */
export async function loadMemeTemplates(): Promise<MemeTemplate[]> {
  const manifestUrl = `${import.meta.env.BASE_URL}memes/index.json`;
  let manifestResponse: Response;
  try {
    manifestResponse = await fetch(manifestUrl);
  } catch (err) {
    console.warn('Failed to fetch meme manifest:', err);
    return [];
  }

  if (!manifestResponse.ok) {
    console.warn(`Failed to fetch meme manifest: HTTP ${manifestResponse.status}`);
    return [];
  }

  let entries: unknown;
  try {
    entries = await manifestResponse.json();
  } catch (err) {
    console.warn('Meme manifest is not valid JSON:', err);
    return [];
  }

  if (!Array.isArray(entries)) {
    console.warn('Meme manifest must be a JSON array of template objects.');
    return [];
  }

  return entries
    .map((entry, index) => {
      if (!isMemeTemplate(entry)) {
        const label =
          entry && typeof entry === 'object' && 'id' in entry && typeof (entry as { id: unknown }).id === 'string'
            ? (entry as { id: string }).id
            : `index ${index}`;
        console.warn(`Skipped invalid meme template: ${label}`);
        return null;
      }
      return { ...entry, url: resolveTemplateUrl(entry.url) };
    })
    .filter((template): template is MemeTemplate => template !== null)
    .sort((a, b) => a.name.localeCompare(b.name));
}
