import type { MemeTemplate, MemeThumbnailCrop } from '../types';
import { isMemeTemplate } from '../utils/memeTemplate';
import { resolveTemplateImageUrl } from '../utils/templateImport';

/**
 * Validate an optional thumbnail crop. Returns the crop when it is well-formed,
 * `null` when it should be dropped (warns the caller-supplied label so authors
 * notice in the console), and `undefined` when the field is absent.
 *
 * NOTE: we do NOT check that `width / height === 4/3`. The crop is stored in
 * normalized (0..1) image coordinates, where the ratio between normalized w
 * and h depends on the source image's own aspect ratio — only the
 * pixel-space crop is guaranteed 4:3. A non-square image will always produce
 * a non-4/3 normalized ratio. The Gallery card enforces 4:3 via its CSS
 * container, so any well-formed crop renders correctly.
 */
function validateThumbnail(value: unknown, label: string): MemeThumbnailCrop | null | undefined {
  if (value === undefined || value === null) {
    return undefined;
  }
  if (typeof value !== 'object') {
    console.warn(`Template "${label}" has a non-object thumbnail; ignoring.`);
    return null;
  }
  const crop = value as Partial<MemeThumbnailCrop>;
  const numbers: (keyof MemeThumbnailCrop)[] = ['x', 'y', 'width', 'height'];
  for (const key of numbers) {
    const num = crop[key];
    if (typeof num !== 'number' || !Number.isFinite(num) || num < 0 || num > 1) {
      console.warn(`Template "${label}" has an out-of-range thumbnail.${key}; ignoring crop.`);
      return null;
    }
  }
  const { x, y, width, height } = crop as MemeThumbnailCrop;
  if (width <= 0 || height <= 0 || x + width > 1 + 1e-6 || y + height > 1 + 1e-6) {
    console.warn(`Template "${label}" has a thumbnail that escapes the image; ignoring crop.`);
    return null;
  }
  return { x, y, width, height };
}

/**
 * Loads all meme templates with a single network round-trip.
 *
 * `public/memes/index.json` is generated by `vite-plugin-meme-manifest` and
 * inlines every template's full JSON, so we don't pay N+1 fetches as the
 * template count grows.
 *
 * To add a template: drop a PNG/JPG/SVG into `public/memes/` and a sibling
 * JSON next to it — the plugin updates the manifest on the next dev tick or
 * build. Invalid entries are warned to console and skipped, not thrown.
 */
export async function loadMemeTemplates(): Promise<MemeTemplate[]> {
  const manifestUrl = `${import.meta.env.BASE_URL}memes/index.json`;
  let manifestResponse: Response;
  try {
    manifestResponse = await fetch(manifestUrl);
  } catch (err) {
    console.warn('Failed to fetch meme manifest:', err);
    return [];
  }

  if (!manifestResponse.ok) {
    console.warn(`Failed to fetch meme manifest: HTTP ${manifestResponse.status}`);
    return [];
  }

  let entries: unknown;
  try {
    entries = await manifestResponse.json();
  } catch (err) {
    console.warn('Meme manifest is not valid JSON:', err);
    return [];
  }

  if (!Array.isArray(entries)) {
    console.warn('Meme manifest must be a JSON array of template objects.');
    return [];
  }

  return entries
    .map((entry, index) => {
      if (!isMemeTemplate(entry)) {
        const label =
          entry && typeof entry === 'object' && 'id' in entry && typeof (entry as { id: unknown }).id === 'string'
            ? (entry as { id: string }).id
            : `index ${index}`;
        console.warn(`Skipped invalid meme template: ${label}`);
        return null;
      }
      const thumbnail = validateThumbnail((entry as { thumbnail?: unknown }).thumbnail, entry.id);
      const { thumbnail: _stripped, ...rest } = entry as MemeTemplate & { thumbnail?: unknown };
      void _stripped;
      const next: MemeTemplate = { ...rest, url: resolveTemplateImageUrl(entry.url, import.meta.env.BASE_URL) };
      if (thumbnail) {
        next.thumbnail = thumbnail;
      }
      return next;
    })
    .filter((template): template is MemeTemplate => template !== null)
    .sort((a, b) => a.name.localeCompare(b.name));
}
